# Parameters related to building rocblas
ARG base_image

FROM ${base_image}
LABEL maintainer="rocblas-examples.maintainer@amd.com"

ARG user_uid

# Install dependent packages
RUN yum install -y \
    sudo \
    rocm-dev \
    centos-release-scl \
    devtoolset-7 \
    ca-certificates \
    git \
    make \
    gcc-c++ \
    unzip \
    wget \
    libcxx-devel \
    zlib-devel \ 
    numactl-libs

# Remove old rocblas rpm already in CentOS docker image
RUN yum remove -y rocblas

RUN echo '#!/bin/bash' | tee /etc/profile.d/devtoolset7.sh && echo \
    'source scl_source enable devtoolset-7' >>/etc/profile.d/devtoolset7.sh

# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd
